#ifndef CUBELL_BSL_BOARD_CONFIG_H
#define CUBELL_BSL_BOARD_CONFIG_H
#include "main.h"
static inline void bsl_boardConfigureGpio(void){ LL_GPIO_InitTypeDef i={0}; LL_AHB2_GRP1_EnableClock(LL_AHB2_GRP1_PERIPH_GPIOC|LL_AHB2_GRP1_PERIPH_GPIOB); i.Pin=B1_Pin;i.Mode=LL_GPIO_MODE_INPUT;i.Speed=LL_GPIO_SPEED_FREQ_LOW;i.OutputType=LL_GPIO_OUTPUT_PUSHPULL;i.Pull=LL_GPIO_PULL_NO;i.Alternate=LL_GPIO_AF_0;LL_GPIO_Init(B1_GPIO_Port,&i); i.Pin=LD4_Pin;i.Mode=LL_GPIO_MODE_OUTPUT;LL_GPIO_Init(LD4_GPIO_Port,&i); }
static inline void bsl_boardConfigureGpioMultiEx(void){
 LL_GPIO_InitTypeDef i={0}; LL_AHB2_GRP1_EnableClock(LL_AHB2_GRP1_PERIPH_GPIOA|LL_AHB2_GRP1_PERIPH_GPIOB|LL_AHB2_GRP1_PERIPH_GPIOC|LL_AHB2_GRP1_PERIPH_GPIOD|LL_AHB2_GRP1_PERIPH_GPIOE|LL_AHB2_GRP1_PERIPH_GPIOH);
 #define INIT(PORT,PIN,MODE,SPEED,TYPE,PULL) do{i.Pin=(PIN);i.Mode=(MODE);i.Speed=(SPEED);i.OutputType=(TYPE);i.Pull=(PULL);i.Alternate=LL_GPIO_AF_0;LL_GPIO_Init((PORT),&i);}while(0)
 INIT(GPIOC,LL_GPIO_PIN_13,LL_GPIO_MODE_INPUT,LL_GPIO_SPEED_FREQ_LOW,LL_GPIO_OUTPUT_PUSHPULL,LL_GPIO_PULL_NO); INIT(GPIOB,LL_GPIO_PIN_13,LL_GPIO_MODE_OUTPUT,LL_GPIO_SPEED_FREQ_LOW,LL_GPIO_OUTPUT_PUSHPULL,LL_GPIO_PULL_NO);
 INIT(GPIOA,LL_GPIO_PIN_0,LL_GPIO_MODE_INPUT,LL_GPIO_SPEED_FREQ_LOW,LL_GPIO_OUTPUT_PUSHPULL,LL_GPIO_PULL_UP); INIT(GPIOB,LL_GPIO_PIN_0,LL_GPIO_MODE_OUTPUT,LL_GPIO_SPEED_FREQ_MEDIUM,LL_GPIO_OUTPUT_PUSHPULL,LL_GPIO_PULL_UP);
 INIT(GPIOA,LL_GPIO_PIN_1,LL_GPIO_MODE_INPUT,LL_GPIO_SPEED_FREQ_LOW,LL_GPIO_OUTPUT_PUSHPULL,LL_GPIO_PULL_DOWN); INIT(GPIOB,LL_GPIO_PIN_1,LL_GPIO_MODE_OUTPUT,LL_GPIO_SPEED_FREQ_HIGH,LL_GPIO_OUTPUT_OPENDRAIN,LL_GPIO_PULL_DOWN);
 INIT(GPIOA,LL_GPIO_PIN_2,LL_GPIO_MODE_INPUT,LL_GPIO_SPEED_FREQ_LOW,LL_GPIO_OUTPUT_PUSHPULL,LL_GPIO_PULL_NO); INIT(GPIOB,LL_GPIO_PIN_2,LL_GPIO_MODE_OUTPUT,LL_GPIO_SPEED_FREQ_VERY_HIGH,LL_GPIO_OUTPUT_PUSHPULL,LL_GPIO_PULL_NO);
 INIT(GPIOA,LL_GPIO_PIN_3,LL_GPIO_MODE_INPUT,LL_GPIO_SPEED_FREQ_LOW,LL_GPIO_OUTPUT_PUSHPULL,LL_GPIO_PULL_UP); INIT(GPIOB,LL_GPIO_PIN_3,LL_GPIO_MODE_OUTPUT,LL_GPIO_SPEED_FREQ_LOW,LL_GPIO_OUTPUT_OPENDRAIN,LL_GPIO_PULL_UP);
 INIT(GPIOC,LL_GPIO_PIN_4,LL_GPIO_MODE_INPUT,LL_GPIO_SPEED_FREQ_LOW,LL_GPIO_OUTPUT_PUSHPULL,LL_GPIO_PULL_DOWN); INIT(GPIOB,LL_GPIO_PIN_4,LL_GPIO_MODE_OUTPUT,LL_GPIO_SPEED_FREQ_MEDIUM,LL_GPIO_OUTPUT_PUSHPULL,LL_GPIO_PULL_DOWN);
 INIT(GPIOC,LL_GPIO_PIN_5,LL_GPIO_MODE_INPUT,LL_GPIO_SPEED_FREQ_LOW,LL_GPIO_OUTPUT_PUSHPULL,LL_GPIO_PULL_NO); INIT(GPIOB,LL_GPIO_PIN_5,LL_GPIO_MODE_OUTPUT,LL_GPIO_SPEED_FREQ_HIGH,LL_GPIO_OUTPUT_OPENDRAIN,LL_GPIO_PULL_NO);
 INIT(GPIOD,LL_GPIO_PIN_6,LL_GPIO_MODE_INPUT,LL_GPIO_SPEED_FREQ_LOW,LL_GPIO_OUTPUT_PUSHPULL,LL_GPIO_PULL_UP); INIT(GPIOE,LL_GPIO_PIN_6,LL_GPIO_MODE_OUTPUT,LL_GPIO_SPEED_FREQ_VERY_HIGH,LL_GPIO_OUTPUT_PUSHPULL,LL_GPIO_PULL_UP);
 INIT(GPIOE,LL_GPIO_PIN_7,LL_GPIO_MODE_INPUT,LL_GPIO_SPEED_FREQ_LOW,LL_GPIO_OUTPUT_PUSHPULL,LL_GPIO_PULL_DOWN); INIT(GPIOH,LL_GPIO_PIN_0,LL_GPIO_MODE_OUTPUT,LL_GPIO_SPEED_FREQ_LOW,LL_GPIO_OUTPUT_OPENDRAIN,LL_GPIO_PULL_DOWN);
 #undef INIT
}
#endif
