/**
  ******************************************************************************
  * @file      startup_stm32l433rctxp.s
  * @author    Auto-generated by STM32CubeIDE
  * @Abstract : Startup script for STM32L433RCTxP Device
  * @version   V1.0.0
  * @date      2019-06-04
  ******************************************************************************
  */

.syntax unified
.cpu cortex-m4
.fpu softvfp
.thumb

.global g_pfnVectors
.global Default_Handler

/* start address for the initialization values of the .data section.
defined in linker script */
.word _sidata
/* start address for the .data section. defined in linker script */
.word _sdata
/* end address for the .data section. defined in linker script */
.word _edata
/* start address for the .bss section. defined in linker script */
.word _sbss
/* end address for the .bss section. defined in linker script */
.word _ebss


/**
 * @brief  This is the code that gets called when the processor first
 *          starts execution following a reset event. Only the absolutely
 *          necessary set is performed, after which the application
 *          supplied main() routine is called.
 * @param  None
 * @retval : None
*/

  .section .text.Reset_Handler
  .weak Reset_Handler
  .type Reset_Handler, %function
Reset_Handler:
  ldr   r0, =_estack
  mov   sp, r0          /* set stack pointer */

/* Copy the data segment initializers from flash to SRAM */

  ldr r0, =_sdata
  ldr r1, =_edata
  ldr r2, =_sidata
  movs r3, #0
  b LoopCopyDataInit

CopyDataInit:


  ldr r4, [r2, r3]
  str r4, [r0, r3]
  adds r3, r3, #4

LoopCopyDataInit:


  adds r4, r0, r3
  cmp r4, r1



  bcc CopyDataInit

/* Zero fill the bss segment. */
  ldr r2, =_sbss
  ldr r4, =_ebss
  movs r3, #0
  b LoopFillZerobss

FillZerobss:

  str  r3, [r2]
  adds r2, r2, #4

LoopFillZerobss:

  cmp r2, r4
  bcc FillZerobss

/* Call static constructors */
  bl __libc_init_array
/* Call the application's entry point.*/
  bl main

LoopForever:
    b LoopForever



.size Reset_Handler, .-Reset_Handler

/**
 * @brief  This is the code that gets called when the processor receives an
 *         unexpected interrupt.  This simply enters an infinite loop, preserving
 *         the system state for examination by a debugger.
 *
 * @param  None
 * @retval : None
*/
    .section .text.Default_Handler,"ax",%progbits
Default_Handler:
Infinite_Loop:
  b Infinite_Loop
  .size Default_Handler, .-Default_Handler
/******************************************************************************
*
* The STM32L433RCTxP vector table.  Note that the proper constructs
* must be placed on this to ensure that it ends up at physical address
* 0x0000.0000.
*
******************************************************************************/
   .section .isr_vector,"a",%progbits
  .type g_pfnVectors, %object
  .size g_pfnVectors, .-g_pfnVectors


g_pfnVectors:
  .word _estack
  .word Reset_Handler
  .word Default_Handler
  .word Default_Handler
  .word	Default_Handler
  .word	Default_Handler
  .word	Default_Handler
  .word	0
  .word	0
  .word	0
  .word	0
  .word	Default_Handler
  .word	Default_Handler
  .word	0
  .word	Default_Handler
  .word	Default_Handler
  .word	Default_Handler         			/* Window Watchdog interrupt                                           */
  .word	Default_Handler          			/* PVD through EXTI line detection                                     */
  .word	Default_Handler   			/* Tamper and TimeStamp interrupts                                     */
  .word	Default_Handler     			/* RTC Tamper or TimeStamp /CSS on LSE through EXTI line 19 interrupts */
  .word	Default_Handler        			/* Flash global interrupt                                              */
  .word	Default_Handler          			/* RCC global interrupt                                                */
  .word	Default_Handler        			/* EXTI Line 0 interrupt                                               */
  .word	Default_Handler        			/* EXTI Line 1 interrupt                                               */
  .word	Default_Handler        			/* EXTI Line 2 interrupt                                               */
  .word	Default_Handler        			/* EXTI Line 3 interrupt                                               */
  .word	Default_Handler        			/* EXTI Line4 interrupt                                                */
  .word	Default_Handler			/* DMA1 Channel1 global interrupt                                      */
  .word	Default_Handler			/* DMA1 Channel2 global interrupt                                      */
  .word	Default_Handler			/* DMA1 Channel3 interrupt                                             */
  .word	Default_Handler			/* DMA1 Channel4 interrupt                                             */
  .word	Default_Handler			/* DMA1 Channel5 interrupt                                             */
  .word	Default_Handler			/* DMA1 Channel6 interrupt                                             */
  .word	Default_Handler			/* DMA1 Channel 7 interrupt                                            */
  .word	Default_Handler         			/* ADC1 and ADC2 global interrupt                                      */
  .word	Default_Handler      			/* CAN1 TX interrupts                                                  */
  .word	Default_Handler     			/* CAN1 RX0 interrupts                                                 */
  .word	Default_Handler     			/* CAN1 RX1 interrupts                                                 */
  .word	Default_Handler     			/* CAN1 SCE interrupt                                                  */
  .word	Default_Handler      			/* EXTI Line5 to Line9 interrupts                                      */
  .word	Default_Handler        			/* Timer 15 global interrupt                                           */
  .word	Default_Handler        			/* Timer 16 global interrupt                                           */
  .word	0                       			/* Reserved                                                            */
  .word	Default_Handler      			/* TIM1 Capture Compare interrupt                                      */
  .word	Default_Handler         			/* TIM2 global interrupt                                               */
  .word	0                       			/* Reserved                                                            */
  .word	0                       			/* Reserved                                                            */
  .word	Default_Handler      			/* I2C1 event interrupt                                                */
  .word	Default_Handler      			/* I2C1 error interrupt                                                */
  .word	Default_Handler      			/* I2C2 event interrupt                                                */
  .word	Default_Handler      			/* I2C2 error interrupt                                                */
  .word	Default_Handler         			/* SPI1 global interrupt                                               */
  .word	Default_Handler         			/* SPI2 global interrupt                                               */
  .word	Default_Handler       			/* USART1 global interrupt                                             */
  .word	Default_Handler       			/* USART2 global interrupt                                             */
  .word	Default_Handler       			/* USART3 global interrupt                                             */
  .word	Default_Handler    			/* EXTI Lines 10 to 15 interrupts                                      */
  .word	Default_Handler    			/* RTC alarms through EXTI line 18 interrupts                          */
  .word	0                       			/* Reserved                                                            */
  .word	0                       			/* Reserved                                                            */
  .word	0                       			/* Reserved                                                            */
  .word	0                       			/* Reserved                                                            */
  .word	0                       			/* Reserved                                                            */
  .word	Default_Handler         			/* ADC3 global Interrupt                                               */
  .word	0                       			/* Reserved                                                            */
  .word	Default_Handler        			/* SDMMC global Interrupt                                              */
  .word	0                       			/* Reserved                                                            */
  .word	Default_Handler         			/* SPI3 global Interrupt                                               */
  .word	0                       			/* Reserved                                                            */
  .word	0                       			/* Reserved                                                            */
  .word	Default_Handler     			/* TIM6 global and DAC1 and 2 underrun error interrupts                */
  .word	Default_Handler         			/* TIM7 global interrupt                                               */
  .word	Default_Handler			/* DMA2 Channel 1 global Interrupt                                     */
  .word	Default_Handler			/* DMA2 Channel 2 global Interrupt                                     */
  .word	Default_Handler			/* DMA2 Channel 3 global Interrupt                                     */
  .word	Default_Handler			/* DMA2 Channel 4 global Interrupt                                     */
  .word	Default_Handler			/* DMA2 Channel 5 global Interrupt                                     */
  .word	0                       			/* Reserved                                                            */
  .word	0                       			/* Reserved                                                            */
  .word	0                       			/* Reserved                                                            */
  .word	Default_Handler         			/* COMP1 and COMP2 interrupts                                          */
  .word	Default_Handler       			/* LP TIM1 interrupt                                                   */
  .word	Default_Handler       			/* LP TIM2 interrupt                                                   */
  .word	0                       			/* Reserved                                                            */
  .word	Default_Handler			/* DMA2 Channel 6 global Interrupt                                     */
  .word	Default_Handler			/* DMA2 Channel 7 global Interrupt                                     */
  .word	0                       			/* Reserved                                                            */
  .word	0                       			/* Reserved                                                            */
  .word	Default_Handler      			/* I2C3 event interrupt                                                */
  .word	Default_Handler      			/* I2C3 error interrupt                                                */
  .word	Default_Handler         			/* SAI1 global interrupt                                               */
  .word	0                       			/* Reserved                                                            */
  .word	Default_Handler       			/* SWPMI1 global interrupt                                             */
  .word	Default_Handler          			/* TSC global interrupt                                                */
  .word	Default_Handler          			/* LCD global interrupt                                                */
  .word	Default_Handler          			/* RNG global interrupt                                                */
  .word	Default_Handler          			/* CRS global interrupt                                                */
  .word	Default_Handler          			/* Floating point interrupt                                            */
