set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(ARM_GCC_PREFIX "arm-none-eabi" CACHE STRING "GNU Arm Embedded toolchain prefix")

find_program(ARM_GCC_C_COMPILER NAMES ${ARM_GCC_PREFIX}-gcc REQUIRED)
find_program(ARM_GCC_CXX_COMPILER NAMES ${ARM_GCC_PREFIX}-g++ REQUIRED)
find_program(ARM_GCC_ASM_COMPILER NAMES ${ARM_GCC_PREFIX}-gcc REQUIRED)
find_program(ARM_GCC_AR NAMES ${ARM_GCC_PREFIX}-ar REQUIRED)
find_program(ARM_GCC_OBJCOPY NAMES ${ARM_GCC_PREFIX}-objcopy)
find_program(ARM_GCC_SIZE NAMES ${ARM_GCC_PREFIX}-size)

set(CMAKE_C_COMPILER ${ARM_GCC_C_COMPILER})
set(CMAKE_CXX_COMPILER ${ARM_GCC_CXX_COMPILER})
set(CMAKE_ASM_COMPILER ${ARM_GCC_ASM_COMPILER})
set(CMAKE_AR ${ARM_GCC_AR})

if(ARM_GCC_OBJCOPY)
  set(CMAKE_OBJCOPY ${ARM_GCC_OBJCOPY} CACHE FILEPATH "objcopy executable" FORCE)
endif()

if(ARM_GCC_SIZE)
  set(CMAKE_SIZE ${ARM_GCC_SIZE} CACHE FILEPATH "size executable" FORCE)
endif()
